### ISSUE TITLE
config.local.ts

### ISSUE THREAD

**Issue by bunlongheng** [BEE-Plugin/beeplugin-react-starter#4]
As a developer representing Thryv, I am working on integrating Bee with our platform. I am currently trying to get the project up and running, and I noticed in the readme file that it mentions the following:

```
# Open config.local.ts and change  
# the placeholders with your credentials
CLIENT_ID:       '### my-client-id ###'
CLIENT_SECRET:   '### my-secret-key ###'
CLIENT_UID:      '### username ###'
# NOTE: remember to store these credentials in your
# back-end and not expose them publicly in your front-end
```

However, after cloning the repository, I was unable to find the config.local.ts or config.local.sample files. Should we create these files ourselves, or are they supposed to be included in the repository?

Could you please provide further clarification on this matter?

**Comment by rmarchet** [comment]
Hi @bunlongheng - The **config.local.ts** is in the **/config** directory.
