### ISSUE TITLE
White Empty Page

### ISSUE THREAD

**Issue by bunlongheng** [BEE-Plugin/beeplugin-react-starter#5]
I've tried to start the project based on your readme. I ran npm start on the beeplugin-react-starter repository and received the following output:

```
Copy code
➜  beeplugin-react-starter git:(master) ✗ npm start  

> beeplugin-react-starter@1.0.2 start
> webpack serve --open

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from ./
ℹ ｢wdm｣: wait until bundle finished: /
ℹ ｢wdm｣: asset bundle.js 1.48 MiB [emitted] (name: main)
runtime modules 1010 bytes 5 modules
modules by path ./node_modules/ 1.4 MiB 40 modules
modules by path ./src/ 4.31 KiB
  ./src/index.tsx 310 bytes [built] [code generated]
  ./src/containers/BeePage.tsx 851 bytes [built] [code generated]
  ./src/components/Bee.tsx 3.17 KiB [built] [code generated]
./config/config.local.ts 255 bytes [built] [code generated]
webpack 5.78.0 compiled successfully in 1368 ms
ℹ ｢wdm｣: Compiled successfully.
```

![Screenshot 2023-04-09 at 17 07 40](https://user-images.githubusercontent.com/11523064/230796678-2361c08a-1318-4fa1-ac55-4690f1a6e4d0.png)

However, when I visited the site, I only saw a white empty page. How can I further debug this issue?

**Comment by rmarchet** [comment]
Hi @bunlongheng - Once valid clientId, clientSecret and UID are provided in the **config.local.ts** file, the application starts correctly and the Editor is rendered in the window.
